# Generated by Django 3.1.5 on 2021-03-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsApp', '0003_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewsApp.resturants'),
        ),
    ]
